CREATE SEQUENCE beszallito_seq START WITH 1000;
CREATE SEQUENCE raktaros_seq START WITH 2000;
CREATE SEQUENCE raktar_seq START WITH 3000;
CREATE SEQUENCE reszleg_seq START WITH 4000;
CREATE SEQUENCE rendeles_seq START WITH 5000;
CREATE SEQUENCE termek_seq START WITH 6000;
