CREATE SEQUENCE supplier_seq START WITH 1000;
CREATE SEQUENCE wh_coordinator_seq START WITH 2000;
CREATE SEQUENCE warehouse_seq START WITH 3000;
CREATE SEQUENCE department_seq START WITH 4000;
CREATE SEQUENCE product_seq START WITH 6000;
CREATE SEQUENCE wh_order_seq START WITH 10000;
CREATE SEQUENCE dept_order_seq START WITH 12000;
CREATE SEQUENCE error_log_seq START WITH 1;




